name: Azure Windows 11 VPS

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          curl -skLO https://raw.githubusercontent.com/gd-discov3r/win_11_vps/main/setup.sh
          chmod +x setup.sh
          ./setup.sh
